# Generates Strings.ru.xaml and Strings.en.xaml from one table.
# Usage: python3 make_strings.py [resources directory]
import sys
from xml.sax.saxutils import escape
S = [
("AppTitle", "Grbl Host — управление станком CNC 3018", "Grbl Host — CNC 3018 control"),
("PortTip", "COM-порт контроллера", "Controller COM port"),
("RefreshPortsTip", "Обновить список портов", "Refresh the port list"),
("BaudTip", "Скорость. Для USB CDC (BlackPill) не важна, для UART — 115200", "Baud rate. Doesn't matter for USB CDC (BlackPill), 115200 for UART"),
("TimeScaleTip", "Во сколько раз виртуальный станок быстрее настоящего", "How many times faster the virtual machine runs than a real one"),
("AddressTip", "Адрес моста Telnet (ESP3D, ser2net, WiFi-UART): IP или имя, порт через двоеточие, по умолчанию 23", "Address of the Telnet bridge (ESP3D, ser2net, WiFi-UART): IP or name, port after a colon, 23 by default"),
("Connect", "Подключить", "Connect"),
("Disconnect", "Отключить", "Disconnect"),
("EStop", "СБРОС", "RESET"),
("EStopTip", "Мягкий сброс (Ctrl-X): всё останавливается сразу, буферы очищаются. В движении grbl теряет позицию (тревога 3)", "Soft reset (Ctrl-X): everything stops at once, the buffers are flushed. In motion grbl loses the position (alarm 3)"),
("FeedHoldTip", "Пауза подачи (!): плавная остановка с торможением", "Feed hold (!): a controlled stop with deceleration"),
("CycleStartTip", "Продолжить (~) после паузы", "Cycle start (~) after a hold"),
("Unlock", "Разблокировать", "Unlock"),
("UnlockTip", "$X — снять блокировку тревоги без поиска нуля. Убедитесь, что позиция верна", "$X — clear the alarm lock without homing. Make sure the position is right"),
("Open", "Открыть", "Open"),
("Demo", "Тест", "Test"),
("DemoTip", "Тестовая программа для 3018: карман 60×40, бобышка, отверстия, линия с врезанием (глубина 1,5 мм, фреза 3,175)", "Test program for the 3018: pocket 60×40, boss, holes, ramped line (1.5 mm deep, 3.175 mm end mill)"),
("ThemeTip", "Светлая / тёмная тема", "Light / dark theme"),
("LanguageTip", "Язык интерфейса: русский / английский", "Interface language: Russian / English"),
("ErrorTitle", "Grbl Host: ошибка", "Grbl Host: error"),
("VirtualMachine", "Виртуальный станок", "Virtual machine"),
("NetworkPort", "Сеть (Telnet)", "Network (Telnet)"),

("TabJob", "Задание", "Job"),
("TabJobTip", "Файл G-кода и его выполнение", "G-code file and running it"),
("TabControl", "Станок", "Machine"),
("TabControlTip", "Координаты, перемещение, ноль, шпиндель, щуп", "Position, jogging, zero, spindle, probe"),
("TabSettings", "Настройки", "Settings"),
("TabSettingsTip", "Параметры grbl ($$)", "grbl settings ($$)"),
("TabTools", "Сервис", "Tools"),
("TabToolsTip", "Макросы, запросы к контроллеру, прошивка", "Macros, controller queries, firmware"),

("State.Disconnected", "Не подключено", "Disconnected"),
("State.Connecting", "Подключение…", "Connecting…"),
("State.Online", "На связи: {0}", "Online: {0}"),
("State.Reconnecting", "Связь потеряна, переподключение…", "Link lost, reconnecting…"),

("Machine.Unknown", "—", "—"),
("Machine.Idle", "Готов", "Idle"),
("Machine.Run", "Работа", "Run"),
("Machine.Hold", "Пауза", "Hold"),
("Machine.Jog", "Перемещение", "Jog"),
("Machine.Alarm", "Тревога", "Alarm"),
("Machine.Door", "Дверь", "Door"),
("Machine.Check", "Проверка", "Check"),
("Machine.Home", "Поиск нуля", "Homing"),
("Machine.Sleep", "Сон", "Sleep"),
("Machine.Tool", "Смена инструмента", "Tool change"),
("Machine.HoldDone", "стоит", "stopped"),
("Machine.Holding", "тормозит", "stopping"),
("Machine.DoorOpen", "открыта", "open"),

("Conn.Online", "Контроллер на связи: {0}", "Controller online: {0}"),
("Conn.LinkLost", "Связь потеряна: {0}", "Link lost: {0}"),
("Conn.LinkTimeout", "Контроллер молчит {0} с", "No answer from the controller for {0} s"),
("Conn.Reconnected", "Связь восстановлена: {0}", "Link restored: {0}"),
("Conn.ControllerReset", "Контроллер перезапустился: {0}", "The controller restarted: {0}"),
("Conn.JobLostOnReset", "Задание прервано: контроллер перезапустился", "Job aborted: the controller restarted"),
("Conn.JobLostOnLinkLoss", "Задание прервано: потеряна связь с контроллером", "Job aborted: the link to the controller was lost"),
("Conn.JobStoppedByError", "Задание остановлено: строка {0}, error:{1} — {2} ({3})", "Job stopped: line {0}, error:{1} — {2} ({3})"),
("Conn.JobStoppedByAlarm", "Задание остановлено тревогой {0}: {1}", "Job stopped by alarm {0}: {1}"),

("Result.Done", "выполнено", "done"),
("Result.Cancelled", "отменено", "cancelled"),
("Result.Error", "ошибка в строке", "error in a line"),
("Result.Alarm", "тревога", "alarm"),
("Result.LinkLost", "потеря связи", "link lost"),
("Result.ControllerReset", "перезапуск контроллера", "controller restart"),

("Feature.Cut", "Резание", "Cut"),
("Feature.Arc", "Дуги", "Arcs"),
("Feature.Plunge", "Врезание", "Plunge"),
("Feature.Retract", "Подъём", "Retract"),
("Feature.Probe", "Щуп", "Probe"),
("Feature.Rapid", "Холостые", "Rapids"),

("File", "Файл", "File"),
("NoFile", "Файл не открыт", "No file open"),
("Loading", "Загрузка {0}…", "Loading {0}…"),
("LoadError", "Не удалось открыть файл", "Couldn't open the file"),
("FileInfo", "{0:N0} строк · {1:0.#} × {2:0.#} × {3:0.##} мм (дно Z {4:0.###}) · ≈ {5} · резание {6:0.##} м · S до {7:0}", "{0:N0} lines · {1:0.#} × {2:0.#} × {3:0.##} mm (bottom Z {4:0.###}) · ≈ {5} · cutting {6:0.##} m · S up to {7:0}"),
("Warn.Unsupported", "Коды, которых grbl не знает: {0} строк ({1})", "Codes grbl doesn't know: {0} lines ({1})"),
("Warn.TooBig", "Программа больше рабочего поля {0} × {1} × {2} мм", "The program is larger than the work area {0} × {1} × {2} mm"),
("Warn.NoSpindle", "В программе нет включения шпинделя (M3 / M4)", "The program never starts the spindle (M3 / M4)"),
("OpenEllipsis", "Открыть…", "Open…"),
("Reload", "Перечитать", "Reload"),
("DemoProgram", "Тестовая программа", "Test program"),
("DropHint", "Файл можно перетащить в окно. G-код: .nc, .gcode, .tap, .ngc", "Drop a file onto the window. G-code: .nc, .gcode, .tap, .ngc"),
("OpenDialogTitle", "Открыть G-код", "Open G-code"),
("OpenDialogFilter", "G-код (*.nc;*.gcode;*.gc;*.ngc;*.tap;*.cnc;*.txt)|*.nc;*.gcode;*.gc;*.ngc;*.tap;*.cnc;*.txt|Все файлы (*.*)|*.*", "G-code (*.nc;*.gcode;*.gc;*.ngc;*.tap;*.cnc;*.txt)|*.nc;*.gcode;*.gc;*.ngc;*.tap;*.cnc;*.txt|All files (*.*)|*.*"),

("RunTitle", "Выполнение", "Run"),
("Start", "Старт", "Start"),
("Pause", "Пауза", "Pause"),
("Resume", "Продолжить", "Resume"),
("Stop", "Стоп", "Stop"),
("Elapsed", "Прошло", "Elapsed"),
("RemainingCap", "  осталось", "  remaining"),
("RunHint", "Строки идут в контроллер с подсчётом символов: буфер приёма grblHAL всегда полон. «Стоп» — пауза подачи, затем сброс, когда станок остановился: позиция сохраняется. Ошибка в строке останавливает задание.", "Lines are streamed with character counting: grblHAL's input buffer stays full. Stop is a feed hold, then a reset once the machine stands: the position is kept. An error in a line stops the job."),
("StartFromTitle", "Старт с середины", "Start in the middle"),
("StartLine", "С строки", "From line"),
("SafeZ", "Безоп. Z", "Safe Z"),
("FromSelectedLine", "С выбранной строки", "From the selected line"),
("StartFromHint", "Перед строкой восстанавливается состояние пропущенных: единицы, режимы, система координат, шпиндель (с паузой на разгон), СОЖ; инструмент поднимается на безопасную высоту, переходит в XY и опускается подачей.", "Before the line the state of the skipped lines is restored: units, modes, coordinate system, spindle (with a spin-up dwell), coolant; the tool goes up to the safe height, moves in XY and comes down at feed."),
("CheckTitle", "Проверка программы", "Program check"),
("CheckMode", "Режим проверки ($C)", "Check mode ($C)"),
("CheckHint", "В режиме проверки grbl разбирает G-код без движения и шпинделя: запустите задание, чтобы найти ошибки. Повторное нажатие выключает режим (со сбросом).", "In check mode grbl parses the G-code without motion or spindle: run the job to find errors. Press again to leave the mode (with a reset)."),

("PositionTitle", "Координаты", "Position"),
("Pins", "Входы:", "Inputs:"),
("Work", "Рабочие", "Work"),
("MachineCoords", "Машинные", "Machine"),
("ZeroTip", "Ноль рабочей системы здесь (G10 L20 P0)", "Work zero here (G10 L20 P0)"),
("ZeroXY", "Ноль XY", "Zero XY"),
("ZeroAll", "Ноль XYZ", "Zero XYZ"),
("GoZeroXY", "В ноль XY", "Go to XY0"),
("GoZeroZ", "В Z0", "Go to Z0"),
("Movement", "Перемещение", "Jog"),
("StepMm", "Шаг, мм", "Step, mm"),
("FeedXY", "Подача XY", "Feed XY"),
("JogCancelTip", "Остановить перемещение (0x85)", "Stop jogging (0x85)"),
("JogHint", "Перемещения — команды $J= в относительных координатах: grblHAL проверяет программные пределы и останавливает их сразу по кнопке ■.", "Jogs are $J= commands in relative coordinates: grblHAL checks the soft limits and stops them at once with the ■ button."),
("Home", "Поиск нуля", "Home"),
("Sleep", "Сон", "Sleep"),
("SpindleTitle", "Шпиндель и СОЖ", "Spindle and coolant"),
("Rpm", "Обороты", "RPM"),
("SpindleCwTip", "Шпиндель по часовой (M3)", "Spindle clockwise (M3)"),
("SpindleCcwTip", "Шпиндель против часовой (M4)", "Spindle counterclockwise (M4)"),
("SpindleOffTip", "Шпиндель выкл. (M5)", "Spindle off (M5)"),
("Flood", "Охлаждение", "Flood"),
("Mist", "Туман", "Mist"),
("CoolantOffTip", "СОЖ выкл. (M9)", "Coolant off (M9)"),
("SpindleNow", "Сейчас:", "Now:"),
("Overrides", "Коррекция", "Overrides"),
("OvFeed", "Подача", "Feed"),
("OvRapid", "Холостые", "Rapids"),
("OvSpindle", "Шпиндель", "Spindle"),
("OverridesHint", "Коррекция работает сразу, в том числе во время задания (команды реального времени).", "Overrides act at once, also while a job runs (real time commands)."),
("ProbeTitle", "Щуп по Z", "Z probe"),
("PlateMm", "Пластина, мм", "Plate, mm"),
("ProbeDistance", "Ход, мм", "Travel, mm"),
("ProbeFeed", "Подача", "Feed"),
("ProbeZ", "Найти Z", "Probe Z"),
("ProbeHint", "G38.2 вниз до касания пластины (вход PB15), затем рабочий Z = толщина пластины и подъём на 2 мм. Не забудьте крокодил на фрезе.", "G38.2 down until the tool touches the plate (input PB15), then work Z = plate thickness and 2 mm up. Don't forget the clip on the tool."),
("Probe.Running", "Поиск…", "Probing…"),
("Probe.Missed", "Пластина не найдена", "The plate wasn't found"),
("Probe.Done", "Касание на машинном Z {0:0.###}, рабочий Z = {1:0.###}", "Touch at machine Z {0:0.###}, work Z = {1:0.###}"),

("SettingsFilter", "Поиск: номер или название", "Search: number or name"),
("ReadSettingsTip", "Прочитать настройки ($$)", "Read the settings ($$)"),
("WriteSettings", "Записать", "Write"),
("SettingsHint", "Изменённые значения выделены; «Записать» отправляет их ($n=значение), grblHAL сохраняет их во flash (сектор 1 STM32F401).", "Changed values are highlighted; Write sends them ($n=value), grblHAL stores them in flash (sector 1 of the STM32F401)."),

("Macros", "Макросы", "Macros"),
("MacroEditor", "Редактор макросов", "Macro editor"),
("MacroName", "Название", "Name"),
("MacroScript", "Команды, по одной в строке", "Commands, one per line"),
("Add", "Добавить", "Add"),
("Delete", "Удалить", "Delete"),
("MacrosHint", "Макросы сохраняются при выходе из программы.", "Macros are saved when the program exits."),
("NewMacro", "Новый макрос", "New macro"),
("Macro.SafeZ", "Z вверх", "Z up"),
("Macro.GoZero", "В ноль", "Go to zero"),
("Macro.Park", "Парковка", "Park"),
("Macro.Frame", "Рамка 60×40", "Frame 60×40"),
("Macro.ToolChange", "Смена фрезы", "Tool change"),
("ChecksTitle", "Запросы", "Queries"),
("BuildInfo", "Версия", "Build info"),
("ParserState", "Режимы", "Parser state"),
("Offsets", "Смещения", "Offsets"),
("StartupLines", "Стартовые строки", "Startup lines"),
("Pinout", "Выводы", "Pins"),
("Help", "Справка", "Help"),
("AnswersHint", "Ответы — в консоли (снимите «скрывать служебные»).", "The answers are in the console (untick \"hide service lines\")."),
("WcsTitle", "Системы координат", "Work coordinate systems"),
("ClearG92", "Сбросить G92", "Clear G92"),
("WcsHint", "G54 — основная. Ноль, заданный на вкладке «Станок», относится к активной системе.", "G54 is the main one. The zero set on the Machine tab applies to the active system."),
("ConnectionTitle", "Соединение", "Connection"),
("AutoReconnect", "Переподключаться автоматически", "Reconnect automatically"),
("AutoReconnectHint", "Если COM-порт пропал или оборвалась сеть, программа раз в секунду открывает соединение заново. Задание при этом прерывается: grbl не может продолжить с середины без сброса. Если контроллер 5 с не отвечает на запрос состояния, соединение тоже открывается заново.", "When the COM port goes away or the network drops, the program opens the connection again every second. A running job is aborted: grbl can't continue in the middle without a reset. With no answer to the status query for 5 s the connection is reopened as well."),
("FirmwareTitle", "Прошивка", "Firmware"),
("Dfu", "Загрузчик DFU", "DFU bootloader"),
("DfuTip", "$DFU — перезапуск в системный загрузчик STM32 для прошивки по USB (STM32CubeProgrammer, dfu-util)", "$DFU — restart into the STM32 system bootloader to flash over USB (STM32CubeProgrammer, dfu-util)"),
("RestoreDefaults", "Сброс настроек", "Restore defaults"),
("ClearOffsets", "Сброс смещений", "Clear offsets"),
("FirmwareHint", "$DFU есть только в прошивке BlackPill из этого проекта. Сброс настроек возвращает значения из cnc3018_defaults.h.", "$DFU exists only in the BlackPill firmware of this project. Restore defaults brings back the values of cnc3018_defaults.h."),

("GCode", "G-код", "G-code"),
("ListingTip", "Щелчок по строке — симуляция до этой строки", "Click a line to simulate up to it"),
("LineOf", "Строка {0:N0} из {1:N0}", "Line {0:N0} of {1:N0}"),
("Console", "Консоль", "Console"),
("ConsolePlaceholder", "G-код или $-команда, Enter — отправить, ↑/↓ — история; ? ! ~ ^X — команды реального времени", "G-code or a $ command, Enter to send, ↑/↓ history; ? ! ~ ^X are real time commands"),
("Send", "Отправить", "Send"),
("Clear", "Очистить", "Clear"),
("AutoScroll", "Прокрутка", "Auto scroll"),
("HideService", "Скрывать служебные", "Hide service lines"),
("HideServiceTip", "ok и ответы на запросы программы ($I, $$, $G, $#)", "ok and the answers to the program's queries ($I, $$, $G, $#)"),
("JobLines", "Строки задания", "Job lines"),

("Mode.Preview", "ПРОСМОТР", "PREVIEW"),
("Mode.Simulation", "СИМУЛЯЦИЯ", "SIMULATION"),
("Mode.Live", "РАБОТА", "LIVE"),
("ViewIso", "Изо", "Iso"),
("ViewIsoTip", "Изометрия", "Isometric"),
("ViewTop", "Сверху", "Top"),
("ViewFront", "Спереди", "Front"),
("Table", "Поле", "Table"),
("ViewBedTip", "Показать всё рабочее поле", "Show the whole work area"),
("ViewResetTip", "Сбросить вид (двойной щелчок)", "Reset the view (double click)"),
("MouseHint", "ЛКМ — вращение · ПКМ / Shift+ЛКМ — сдвиг · колесо — масштаб", "Left drag: rotate · right / Shift+left: pan · wheel: zoom"),
("FitModel", "Программа", "Program"),
("Layer", "Глубина", "Depth"),
("LayerText", "{0} / {1} · Z {2:0.###}", "{0} / {1} · Z {2:0.###}"),
("LayerInfo", "Уровень {0} / {1}   Z = {2:0.###} мм   шаг = {3:0.###} мм", "Level {0} / {1}   Z = {2:0.###} mm   step = {3:0.###} mm"),
("ShowRapids", "Холостые ходы", "Rapid moves"),
("ToolText", "X {0:0.###}  Y {1:0.###}  Z {2:0.###}  F {3:0}", "X {0:0.###}  Y {1:0.###}  Z {2:0.###}  F {3:0}"),
("PrevLayerTip", "Предыдущий уровень", "Previous level"),
("PrevMoveTip", "Предыдущее перемещение", "Previous move"),
("PlayTip", "Симуляция: старт / пауза", "Simulation: start / pause"),
("NextMoveTip", "Следующее перемещение", "Next move"),
("NextLayerTip", "Следующий уровень", "Next level"),
("StopSimTip", "Закончить симуляцию", "End the simulation"),
("SimTimeTip", "Время выполнения (оценка)", "Run time (estimate)"),
("SpeedX", "Скорость ×", "Speed ×"),
("PausedSuffix", "  ·  пауза", "  ·  paused"),
("ElapsedLower", "  прошло", "  elapsed"),
("RemainingLower", "  осталось", "  remaining"),
("BufferText", "буфер {0} / {1}", "buffer {0} / {1}"),

("Notice.ConnectFailed", "Не удалось подключиться", "Couldn't connect"),
("Notice.AddressEmpty", "Укажите адрес моста Telnet", "Enter the address of the Telnet bridge"),
("Notice.LinkLost", "Связь потеряна", "Link lost"),
("Notice.LinkLostText", "Переподключение…", "Reconnecting…"),
("Notice.LinkLostRunning", "Задание прервано, переподключение…", "The job was aborted, reconnecting…"),
("Notice.LinkRestored", "Связь восстановлена", "Link restored"),
("Notice.JobAborted", "Задание прервано", "Job aborted"),
("Notice.JobDone", "Готово", "Done"),
("Notice.JobDoneText", "{0} выполнен за {1}", "{0} finished in {1}"),
("Notice.JobNotStarted", "Задание не запущено", "The job didn't start"),
("Notice.UnlockFirst", "Станок в тревоге: найдите ноль ($H) или разблокируйте ($X)", "The machine is in alarm: home ($H) or unlock ($X) first"),
("Notice.OpenFailed", "Не удалось открыть файл", "Couldn't open the file"),
("Notice.Alarm", "Тревога", "Alarm"),
("Notice.AlarmText", "ALARM:{0} — {1}.", "ALARM:{0} — {1}."),
("Notice.AlarmRehome", "Позиция могла сбиться: найдите ноль или проверьте её перед работой.", "The position may be lost: home or check it before cutting."),
("Notice.Controller", "Контроллер", "Controller"),
("Notice.CommandError", "Команда не выполнена", "Command refused"),
("Notice.BadSetting", "Неверное значение", "Bad value"),
("Notice.BadSettingText", "{0}: «{1}» — не число", "{0}: \"{1}\" isn't a number"),

("Ask.DisconnectWhileRunning", "Задание выполняется. Отключиться? Станок продолжит отрабатывать то, что уже в буфере.", "A job is running. Disconnect? The machine will run what is already in its buffer."),
("Ask.CloseWhileRunning", "Задание выполняется. Закрыть программу?", "A job is running. Close the program?"),
("Ask.StopJob", "Остановить задание?", "Stop the job?"),
("Ask.StartFromLine", "Начать со строки {0}? Инструмент поднимется на Z {1} и перейдёт в начальную точку. Проверьте, что ноль не сбит.", "Start from line {0}? The tool goes up to Z {1} and moves to the start point. Check that the zero is still right."),
("Ask.ProbeTitle", "Щуп", "Probe"),
("Ask.Probe", "Пластина {0} мм под фрезой, крокодил на фрезе? Z пойдёт вниз до касания.", "Plate ({0} mm) under the tool, clip on the tool? Z goes down until it touches."),
("Ask.Raw.DFU", "Перезапустить контроллер в загрузчик ({0})? Связь пропадёт до следующей прошивки или сброса.", "Restart the controller into the bootloader ({0})? The link is gone until it is flashed or reset."),
("Ask.Raw.RSTS", "Вернуть все настройки по умолчанию ({0})?", "Restore all settings to defaults ({0})?"),
("Ask.Raw.RSTH", "Стереть смещения G54…G59, G28, G30 ({0})?", "Clear the G54…G59, G28, G30 offsets ({0})?"),

("Log.Connecting", "Подключение к {0}, {1} бод…", "Connecting to {0} at {1} baud…"),
("Log.ConnectingNetwork", "Подключение к {0}:{1}…", "Connecting to {0}:{1}…"),
("Log.ConnectingVirtual", "Виртуальный станок, время ×{0}", "Virtual machine, time ×{0}"),
("Log.PortFailed", "Порт не открылся: {0}", "The port didn't open: {0}"),
("Log.Disconnected", "Отключено", "Disconnected"),
("Log.Opened", "Открыт {0}: {1:N0} строк, {2} уровней по глубине", "Opened {0}: {1:N0} lines, {2} depth levels"),
("Log.JobStarted", "Старт {0}: {1:N0} строк, с строки {2}", "Started {0}: {1:N0} lines, from line {2}"),
("Log.JobDone", "Задание выполнено за {0}", "Job done in {0}"),
("Log.JobCancelled", "Задание остановлено", "Job stopped"),
("Log.JobAborted", "Задание прервано: {0}", "Job aborted: {0}"),
("Log.Stopping", "Остановка: пауза подачи, затем сброс", "Stopping: feed hold, then a reset"),
("Log.Pause", "Пауза", "Paused"),
("Log.Resume", "Продолжение", "Resumed"),
("Log.LongLine", "Строка {0} длиннее 256 символов, grbl её не примет", "Line {0} is longer than 256 characters, grbl won't take it"),
("Log.Macro", "Макрос «{0}»", "Macro \"{0}\""),
("Log.SoftReset", "Мягкий сброс (Ctrl-X)", "Soft reset (Ctrl-X)"),
("Log.SettingsWritten", "Записано настроек: {0}", "Settings written: {0}"),
("Log.CommandError", "{0}: error:{1} — {2}", "{0}: error:{1} — {2}"),
("Log.EstimateOld", "Оценка времени посчитана до чтения настроек станка, перечитайте файл для точной", "The time estimate was made before the machine settings were read, reload the file for an exact one"),
]

def write(path, col):
    with open(path, "w", encoding="utf-8") as f:
        f.write('<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"\n')
        f.write('                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"\n')
        f.write('                    xmlns:sys="clr-namespace:System;assembly=System.Runtime">\n')
        f.write('    <!-- Generated from one table with the other language; keep the keys in sync. -->\n')
        for row in S:
            key, text = row[0], row[col]
            text = escape(text, {'"': '&quot;'})
            sp = ' xml:space="preserve"' if text != text.strip() else ''
            f.write(f'    <sys:String x:Key="S.{key}"{sp}>{text}</sys:String>\n')
        f.write('</ResourceDictionary>\n')

keys = [r[0] for r in S]
dup = {k for k in keys if keys.count(k) > 1}
if dup:
    sys.exit("duplicate keys: %s" % dup)
out = sys.argv[1] if len(sys.argv) > 1 else __import__("os").path.dirname(__import__("os").path.abspath(__file__))
write(out + "/Strings.ru.xaml", 1)
write(out + "/Strings.en.xaml", 2)
print(len(S), "strings")
